/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppLanguageRouteRouteImport } from './routes/_app/language/route'
import { Route as AppCurriculumRouteRouteImport } from './routes/_app/curriculum/route'
import { Route as AppHubRouteRouteImport } from './routes/_app/_hub/route'
import { Route as AppSubjectsIndexRouteImport } from './routes/_app/subjects/index'
import { Route as AppLanguageCreateRouteImport } from './routes/_app/language/create'
import { Route as AppLanguageLanguageIdRouteImport } from './routes/_app/language/$languageId'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app/courses/$courseId'
import { Route as AppHubLanguagesRouteImport } from './routes/_app/_hub/languages'
import { Route as AppHubCoursesRouteImport } from './routes/_app/_hub/courses'
import { Route as AppCurriculumCourseIdIndexRouteImport } from './routes/_app/curriculum/$courseId/index'
import { Route as AppCurriculumCourseIdLessonLessonIdRouteImport } from './routes/_app/curriculum/$courseId/lesson/$lessonId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLanguageRouteRoute = AppLanguageRouteRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCurriculumRouteRoute = AppCurriculumRouteRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubRouteRoute = AppHubRouteRouteImport.update({
  id: '/_hub',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLanguageCreateRoute = AppLanguageCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppLanguageRouteRoute,
} as any)
const AppLanguageLanguageIdRoute = AppLanguageLanguageIdRouteImport.update({
  id: '/$languageId',
  path: '/$languageId',
  getParentRoute: () => AppLanguageRouteRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubLanguagesRoute = AppHubLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubCoursesRoute = AppHubCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppCurriculumCourseIdIndexRoute =
  AppCurriculumCourseIdIndexRouteImport.update({
    id: '/$courseId/',
    path: '/$courseId/',
    getParentRoute: () => AppCurriculumRouteRoute,
  } as any)
const AppCurriculumCourseIdLessonLessonIdRoute =
  AppCurriculumCourseIdLessonLessonIdRouteImport.update({
    id: '/$courseId/lesson/$lessonId',
    path: '/$courseId/lesson/$lessonId',
    getParentRoute: () => AppCurriculumRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/curriculum': typeof AppCurriculumRouteRouteWithChildren
  '/language': typeof AppLanguageRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/courses': typeof AppHubCoursesRoute
  '/languages': typeof AppHubLanguagesRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/language/$languageId': typeof AppLanguageLanguageIdRoute
  '/language/create': typeof AppLanguageCreateRoute
  '/subjects': typeof AppSubjectsIndexRoute
  '/curriculum/$courseId': typeof AppCurriculumCourseIdIndexRoute
  '/curriculum/$courseId/lesson/$lessonId': typeof AppCurriculumCourseIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/curriculum': typeof AppCurriculumRouteRouteWithChildren
  '/language': typeof AppLanguageRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/courses': typeof AppHubCoursesRoute
  '/languages': typeof AppHubLanguagesRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/language/$languageId': typeof AppLanguageLanguageIdRoute
  '/language/create': typeof AppLanguageCreateRoute
  '/subjects': typeof AppSubjectsIndexRoute
  '/curriculum/$courseId': typeof AppCurriculumCourseIdIndexRoute
  '/curriculum/$courseId/lesson/$lessonId': typeof AppCurriculumCourseIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_hub': typeof AppHubRouteRouteWithChildren
  '/_app/curriculum': typeof AppCurriculumRouteRouteWithChildren
  '/_app/language': typeof AppLanguageRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/_hub/courses': typeof AppHubCoursesRoute
  '/_app/_hub/languages': typeof AppHubLanguagesRoute
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/_app/language/$languageId': typeof AppLanguageLanguageIdRoute
  '/_app/language/create': typeof AppLanguageCreateRoute
  '/_app/subjects/': typeof AppSubjectsIndexRoute
  '/_app/curriculum/$courseId/': typeof AppCurriculumCourseIdIndexRoute
  '/_app/curriculum/$courseId/lesson/$lessonId': typeof AppCurriculumCourseIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/curriculum'
    | '/language'
    | '/'
    | '/auth'
    | '/courses'
    | '/languages'
    | '/courses/$courseId'
    | '/language/$languageId'
    | '/language/create'
    | '/subjects'
    | '/curriculum/$courseId'
    | '/curriculum/$courseId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/curriculum'
    | '/language'
    | '/'
    | '/auth'
    | '/courses'
    | '/languages'
    | '/courses/$courseId'
    | '/language/$languageId'
    | '/language/create'
    | '/subjects'
    | '/curriculum/$courseId'
    | '/curriculum/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_hub'
    | '/_app/curriculum'
    | '/_app/language'
    | '/_app/'
    | '/auth/'
    | '/_app/_hub/courses'
    | '/_app/_hub/languages'
    | '/_app/courses/$courseId'
    | '/_app/language/$languageId'
    | '/_app/language/create'
    | '/_app/subjects/'
    | '/_app/curriculum/$courseId/'
    | '/_app/curriculum/$courseId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/language': {
      id: '/_app/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof AppLanguageRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/curriculum': {
      id: '/_app/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AppCurriculumRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub': {
      id: '/_app/_hub'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppHubRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/subjects/': {
      id: '/_app/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/language/create': {
      id: '/_app/language/create'
      path: '/create'
      fullPath: '/language/create'
      preLoaderRoute: typeof AppLanguageCreateRouteImport
      parentRoute: typeof AppLanguageRouteRoute
    }
    '/_app/language/$languageId': {
      id: '/_app/language/$languageId'
      path: '/$languageId'
      fullPath: '/language/$languageId'
      preLoaderRoute: typeof AppLanguageLanguageIdRouteImport
      parentRoute: typeof AppLanguageRouteRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub/languages': {
      id: '/_app/_hub/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof AppHubLanguagesRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_hub/courses': {
      id: '/_app/_hub/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppHubCoursesRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/curriculum/$courseId/': {
      id: '/_app/curriculum/$courseId/'
      path: '/$courseId'
      fullPath: '/curriculum/$courseId'
      preLoaderRoute: typeof AppCurriculumCourseIdIndexRouteImport
      parentRoute: typeof AppCurriculumRouteRoute
    }
    '/_app/curriculum/$courseId/lesson/$lessonId': {
      id: '/_app/curriculum/$courseId/lesson/$lessonId'
      path: '/$courseId/lesson/$lessonId'
      fullPath: '/curriculum/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof AppCurriculumCourseIdLessonLessonIdRouteImport
      parentRoute: typeof AppCurriculumRouteRoute
    }
  }
}

interface AppHubRouteRouteChildren {
  AppHubCoursesRoute: typeof AppHubCoursesRoute
  AppHubLanguagesRoute: typeof AppHubLanguagesRoute
}

const AppHubRouteRouteChildren: AppHubRouteRouteChildren = {
  AppHubCoursesRoute: AppHubCoursesRoute,
  AppHubLanguagesRoute: AppHubLanguagesRoute,
}

const AppHubRouteRouteWithChildren = AppHubRouteRoute._addFileChildren(
  AppHubRouteRouteChildren,
)

interface AppCurriculumRouteRouteChildren {
  AppCurriculumCourseIdIndexRoute: typeof AppCurriculumCourseIdIndexRoute
  AppCurriculumCourseIdLessonLessonIdRoute: typeof AppCurriculumCourseIdLessonLessonIdRoute
}

const AppCurriculumRouteRouteChildren: AppCurriculumRouteRouteChildren = {
  AppCurriculumCourseIdIndexRoute: AppCurriculumCourseIdIndexRoute,
  AppCurriculumCourseIdLessonLessonIdRoute:
    AppCurriculumCourseIdLessonLessonIdRoute,
}

const AppCurriculumRouteRouteWithChildren =
  AppCurriculumRouteRoute._addFileChildren(AppCurriculumRouteRouteChildren)

interface AppLanguageRouteRouteChildren {
  AppLanguageLanguageIdRoute: typeof AppLanguageLanguageIdRoute
  AppLanguageCreateRoute: typeof AppLanguageCreateRoute
}

const AppLanguageRouteRouteChildren: AppLanguageRouteRouteChildren = {
  AppLanguageLanguageIdRoute: AppLanguageLanguageIdRoute,
  AppLanguageCreateRoute: AppLanguageCreateRoute,
}

const AppLanguageRouteRouteWithChildren =
  AppLanguageRouteRoute._addFileChildren(AppLanguageRouteRouteChildren)

interface AppRouteRouteChildren {
  AppHubRouteRoute: typeof AppHubRouteRouteWithChildren
  AppCurriculumRouteRoute: typeof AppCurriculumRouteRouteWithChildren
  AppLanguageRouteRoute: typeof AppLanguageRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHubRouteRoute: AppHubRouteRouteWithChildren,
  AppCurriculumRouteRoute: AppCurriculumRouteRouteWithChildren,
  AppLanguageRouteRoute: AppLanguageRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
