/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHubRouteRouteImport } from './routes/_app/hub/route'
import { Route as AppCurriculumRouteRouteImport } from './routes/_app/curriculum/route'
import { Route as AppHubCoursesRouteImport } from './routes/_app/hub/courses'
import { Route as AppHubBannersRouteImport } from './routes/_app/hub/banners'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app/courses/$courseId'
import { Route as AppCurriculumCourseIdIndexRouteImport } from './routes/_app/curriculum/$courseId/index'
import { Route as AppCurriculumCourseIdLessonLessonIdRouteImport } from './routes/_app/curriculum/$courseId/lesson/$lessonId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubRouteRoute = AppHubRouteRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCurriculumRouteRoute = AppCurriculumRouteRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubCoursesRoute = AppHubCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubBannersRoute = AppHubBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCurriculumCourseIdIndexRoute =
  AppCurriculumCourseIdIndexRouteImport.update({
    id: '/$courseId/',
    path: '/$courseId/',
    getParentRoute: () => AppCurriculumRouteRoute,
  } as any)
const AppCurriculumCourseIdLessonLessonIdRoute =
  AppCurriculumCourseIdLessonLessonIdRouteImport.update({
    id: '/$courseId/lesson/$lessonId',
    path: '/$courseId/lesson/$lessonId',
    getParentRoute: () => AppCurriculumRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/curriculum': typeof AppCurriculumRouteRouteWithChildren
  '/hub': typeof AppHubRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/hub/banners': typeof AppHubBannersRoute
  '/hub/courses': typeof AppHubCoursesRoute
  '/curriculum/$courseId': typeof AppCurriculumCourseIdIndexRoute
  '/curriculum/$courseId/lesson/$lessonId': typeof AppCurriculumCourseIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/curriculum': typeof AppCurriculumRouteRouteWithChildren
  '/hub': typeof AppHubRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/hub/banners': typeof AppHubBannersRoute
  '/hub/courses': typeof AppHubCoursesRoute
  '/curriculum/$courseId': typeof AppCurriculumCourseIdIndexRoute
  '/curriculum/$courseId/lesson/$lessonId': typeof AppCurriculumCourseIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_app/curriculum': typeof AppCurriculumRouteRouteWithChildren
  '/_app/hub': typeof AppHubRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/_app/hub/banners': typeof AppHubBannersRoute
  '/_app/hub/courses': typeof AppHubCoursesRoute
  '/_app/curriculum/$courseId/': typeof AppCurriculumCourseIdIndexRoute
  '/_app/curriculum/$courseId/lesson/$lessonId': typeof AppCurriculumCourseIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/curriculum'
    | '/hub'
    | '/'
    | '/auth/'
    | '/courses/$courseId'
    | '/hub/banners'
    | '/hub/courses'
    | '/curriculum/$courseId'
    | '/curriculum/$courseId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/curriculum'
    | '/hub'
    | '/'
    | '/auth'
    | '/courses/$courseId'
    | '/hub/banners'
    | '/hub/courses'
    | '/curriculum/$courseId'
    | '/curriculum/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/curriculum'
    | '/_app/hub'
    | '/_app/'
    | '/auth/'
    | '/_app/courses/$courseId'
    | '/_app/hub/banners'
    | '/_app/hub/courses'
    | '/_app/curriculum/$courseId/'
    | '/_app/curriculum/$courseId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hub': {
      id: '/_app/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AppHubRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/curriculum': {
      id: '/_app/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AppCurriculumRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hub/courses': {
      id: '/_app/hub/courses'
      path: '/courses'
      fullPath: '/hub/courses'
      preLoaderRoute: typeof AppHubCoursesRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/hub/banners': {
      id: '/_app/hub/banners'
      path: '/banners'
      fullPath: '/hub/banners'
      preLoaderRoute: typeof AppHubBannersRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/curriculum/$courseId/': {
      id: '/_app/curriculum/$courseId/'
      path: '/$courseId'
      fullPath: '/curriculum/$courseId'
      preLoaderRoute: typeof AppCurriculumCourseIdIndexRouteImport
      parentRoute: typeof AppCurriculumRouteRoute
    }
    '/_app/curriculum/$courseId/lesson/$lessonId': {
      id: '/_app/curriculum/$courseId/lesson/$lessonId'
      path: '/$courseId/lesson/$lessonId'
      fullPath: '/curriculum/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof AppCurriculumCourseIdLessonLessonIdRouteImport
      parentRoute: typeof AppCurriculumRouteRoute
    }
  }
}

interface AppCurriculumRouteRouteChildren {
  AppCurriculumCourseIdIndexRoute: typeof AppCurriculumCourseIdIndexRoute
  AppCurriculumCourseIdLessonLessonIdRoute: typeof AppCurriculumCourseIdLessonLessonIdRoute
}

const AppCurriculumRouteRouteChildren: AppCurriculumRouteRouteChildren = {
  AppCurriculumCourseIdIndexRoute: AppCurriculumCourseIdIndexRoute,
  AppCurriculumCourseIdLessonLessonIdRoute:
    AppCurriculumCourseIdLessonLessonIdRoute,
}

const AppCurriculumRouteRouteWithChildren =
  AppCurriculumRouteRoute._addFileChildren(AppCurriculumRouteRouteChildren)

interface AppHubRouteRouteChildren {
  AppHubBannersRoute: typeof AppHubBannersRoute
  AppHubCoursesRoute: typeof AppHubCoursesRoute
}

const AppHubRouteRouteChildren: AppHubRouteRouteChildren = {
  AppHubBannersRoute: AppHubBannersRoute,
  AppHubCoursesRoute: AppHubCoursesRoute,
}

const AppHubRouteRouteWithChildren = AppHubRouteRoute._addFileChildren(
  AppHubRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppCurriculumRouteRoute: typeof AppCurriculumRouteRouteWithChildren
  AppHubRouteRoute: typeof AppHubRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCurriculumRouteRoute: AppCurriculumRouteRouteWithChildren,
  AppHubRouteRoute: AppHubRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
