/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppBuildCourseIdRouteImport } from './routes/_app/build/$courseId'

const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBuildCourseIdRoute = AppBuildCourseIdRouteImport.update({
  id: '/_app/build/$courseId',
  path: '/build/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthIndexRoute
  '/build/$courseId': typeof AppBuildCourseIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthIndexRoute
  '/build/$courseId': typeof AppBuildCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth/': typeof AuthIndexRoute
  '/_app/build/$courseId': typeof AppBuildCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/build/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/build/$courseId'
  id: '__root__' | '/auth/' | '/_app/build/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AppBuildCourseIdRoute: typeof AppBuildCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/build/$courseId': {
      id: '/_app/build/$courseId'
      path: '/build/$courseId'
      fullPath: '/build/$courseId'
      preLoaderRoute: typeof AppBuildCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AppBuildCourseIdRoute: AppBuildCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
