/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ResourcesLandingRouteImport } from './routes/resources/landing'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ResourcesLegalRouteRouteImport } from './routes/resources/legal/route'
import { Route as AppSubscriptionRouteRouteImport } from './routes/_app/subscription/route'
import { Route as AppHubRouteRouteImport } from './routes/_app/_hub/route'
import { Route as AppDesktopguardRouteRouteImport } from './routes/_app/_desktopguard/route'
import { Route as ResourcesDocsIndexRouteImport } from './routes/resources/docs/index'
import { Route as ResourcesLegalTosRouteImport } from './routes/resources/legal/tos'
import { Route as ResourcesLegalPrivacyRouteImport } from './routes/resources/legal/privacy'
import { Route as AppSyncLessonIdRouteImport } from './routes/_app/sync/$lessonId'
import { Route as AppSubscriptionSuccessRouteImport } from './routes/_app/subscription/success'
import { Route as AppSubscriptionManageRouteImport } from './routes/_app/subscription/manage'
import { Route as AppSubscriptionConfirmRouteImport } from './routes/_app/subscription/confirm'
import { Route as AppSubscriptionCancelRouteImport } from './routes/_app/subscription/cancel'
import { Route as AppSubscriptionAlreadySubscribedRouteImport } from './routes/_app/subscription/already-subscribed'
import { Route as AppOnboardingStageRouteImport } from './routes/_app/onboarding.$stage'
import { Route as AppHubProjectsRouteImport } from './routes/_app/_hub/projects'
import { Route as AppHubLeaderboardRouteImport } from './routes/_app/_hub/leaderboard'
import { Route as AppHubCoursesRouteImport } from './routes/_app/_hub/courses'
import { Route as AppSubscriptionSubscribedguardRouteRouteImport } from './routes/_app/subscription/_subscribedguard/route'
import { Route as AppSubscriptionSubscribedguardComparisonRouteImport } from './routes/_app/subscription/_subscribedguard/comparison'
import { Route as AppHubProfileUserIdRouteImport } from './routes/_app/_hub/profile/$userId'
import { Route as AppDesktopguardProjectProjectIdRouteImport } from './routes/_app/_desktopguard/project/$projectId'
import { Route as AppHubProfileUserIdIndexRouteImport } from './routes/_app/_hub/profile/$userId/index'
import { Route as AppCompletionCourseIdModuleIdLessonIdRouteImport } from './routes/_app/completion/$courseId/$moduleId/$lessonId'
import { Route as AppHubProfileUserIdSettingsRouteImport } from './routes/_app/_hub/profile/$userId/settings'
import { Route as AppHubLearnCourseIdModuleIdRouteImport } from './routes/_app/_hub/learn/$courseId/$moduleId'
import { Route as AppLessonCourseIdModuleIdLessonIdRouteRouteImport } from './routes/_app/lesson/$courseId/$moduleId/$lessonId/route'
import { Route as AppLessonCourseIdModuleIdLessonIdIndexRouteImport } from './routes/_app/lesson/$courseId/$moduleId/$lessonId/index'

const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ResourcesLandingRoute = ResourcesLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ResourcesLegalRouteRoute = ResourcesLegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const AppSubscriptionRouteRoute = AppSubscriptionRouteRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubRouteRoute = AppHubRouteRouteImport.update({
  id: '/_hub',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDesktopguardRouteRoute = AppDesktopguardRouteRouteImport.update({
  id: '/_desktopguard',
  getParentRoute: () => AppRouteRoute,
} as any)
const ResourcesDocsIndexRoute = ResourcesDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const ResourcesLegalTosRoute = ResourcesLegalTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => ResourcesLegalRouteRoute,
} as any)
const ResourcesLegalPrivacyRoute = ResourcesLegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ResourcesLegalRouteRoute,
} as any)
const AppSyncLessonIdRoute = AppSyncLessonIdRouteImport.update({
  id: '/sync/$lessonId',
  path: '/sync/$lessonId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubscriptionSuccessRoute = AppSubscriptionSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppSubscriptionRouteRoute,
} as any)
const AppSubscriptionManageRoute = AppSubscriptionManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppSubscriptionRouteRoute,
} as any)
const AppSubscriptionConfirmRoute = AppSubscriptionConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AppSubscriptionRouteRoute,
} as any)
const AppSubscriptionCancelRoute = AppSubscriptionCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => AppSubscriptionRouteRoute,
} as any)
const AppSubscriptionAlreadySubscribedRoute =
  AppSubscriptionAlreadySubscribedRouteImport.update({
    id: '/already-subscribed',
    path: '/already-subscribed',
    getParentRoute: () => AppSubscriptionRouteRoute,
  } as any)
const AppOnboardingStageRoute = AppOnboardingStageRouteImport.update({
  id: '/onboarding/$stage',
  path: '/onboarding/$stage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubProjectsRoute = AppHubProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubLeaderboardRoute = AppHubLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubCoursesRoute = AppHubCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppSubscriptionSubscribedguardRouteRoute =
  AppSubscriptionSubscribedguardRouteRouteImport.update({
    id: '/_subscribedguard',
    getParentRoute: () => AppSubscriptionRouteRoute,
  } as any)
const AppSubscriptionSubscribedguardComparisonRoute =
  AppSubscriptionSubscribedguardComparisonRouteImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => AppSubscriptionSubscribedguardRouteRoute,
  } as any)
const AppHubProfileUserIdRoute = AppHubProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppDesktopguardProjectProjectIdRoute =
  AppDesktopguardProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AppDesktopguardRouteRoute,
  } as any)
const AppHubProfileUserIdIndexRoute =
  AppHubProfileUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppHubProfileUserIdRoute,
  } as any)
const AppCompletionCourseIdModuleIdLessonIdRoute =
  AppCompletionCourseIdModuleIdLessonIdRouteImport.update({
    id: '/completion/$courseId/$moduleId/$lessonId',
    path: '/completion/$courseId/$moduleId/$lessonId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppHubProfileUserIdSettingsRoute =
  AppHubProfileUserIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppHubProfileUserIdRoute,
  } as any)
const AppHubLearnCourseIdModuleIdRoute =
  AppHubLearnCourseIdModuleIdRouteImport.update({
    id: '/learn/$courseId/$moduleId',
    path: '/learn/$courseId/$moduleId',
    getParentRoute: () => AppHubRouteRoute,
  } as any)
const AppLessonCourseIdModuleIdLessonIdRouteRoute =
  AppLessonCourseIdModuleIdLessonIdRouteRouteImport.update({
    id: '/lesson/$courseId/$moduleId/$lessonId',
    path: '/lesson/$courseId/$moduleId/$lessonId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLessonCourseIdModuleIdLessonIdIndexRoute =
  AppLessonCourseIdModuleIdLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLessonCourseIdModuleIdLessonIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/subscription': typeof AppSubscriptionSubscribedguardRouteRouteWithChildren
  '/resources/legal': typeof ResourcesLegalRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/resources/landing': typeof ResourcesLandingRoute
  '/': typeof AppIndexRoute
  '/courses': typeof AppHubCoursesRoute
  '/leaderboard': typeof AppHubLeaderboardRoute
  '/projects': typeof AppHubProjectsRoute
  '/onboarding/$stage': typeof AppOnboardingStageRoute
  '/subscription/already-subscribed': typeof AppSubscriptionAlreadySubscribedRoute
  '/subscription/cancel': typeof AppSubscriptionCancelRoute
  '/subscription/confirm': typeof AppSubscriptionConfirmRoute
  '/subscription/manage': typeof AppSubscriptionManageRoute
  '/subscription/success': typeof AppSubscriptionSuccessRoute
  '/sync/$lessonId': typeof AppSyncLessonIdRoute
  '/resources/legal/privacy': typeof ResourcesLegalPrivacyRoute
  '/resources/legal/tos': typeof ResourcesLegalTosRoute
  '/resources/docs': typeof ResourcesDocsIndexRoute
  '/project/$projectId': typeof AppDesktopguardProjectProjectIdRoute
  '/profile/$userId': typeof AppHubProfileUserIdRouteWithChildren
  '/subscription/comparison': typeof AppSubscriptionSubscribedguardComparisonRoute
  '/lesson/$courseId/$moduleId/$lessonId': typeof AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren
  '/learn/$courseId/$moduleId': typeof AppHubLearnCourseIdModuleIdRoute
  '/profile/$userId/settings': typeof AppHubProfileUserIdSettingsRoute
  '/completion/$courseId/$moduleId/$lessonId': typeof AppCompletionCourseIdModuleIdLessonIdRoute
  '/profile/$userId/': typeof AppHubProfileUserIdIndexRoute
  '/lesson/$courseId/$moduleId/$lessonId/': typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/subscription': typeof AppSubscriptionSubscribedguardRouteRouteWithChildren
  '/resources/legal': typeof ResourcesLegalRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/resources/landing': typeof ResourcesLandingRoute
  '/': typeof AppIndexRoute
  '/courses': typeof AppHubCoursesRoute
  '/leaderboard': typeof AppHubLeaderboardRoute
  '/projects': typeof AppHubProjectsRoute
  '/onboarding/$stage': typeof AppOnboardingStageRoute
  '/subscription/already-subscribed': typeof AppSubscriptionAlreadySubscribedRoute
  '/subscription/cancel': typeof AppSubscriptionCancelRoute
  '/subscription/confirm': typeof AppSubscriptionConfirmRoute
  '/subscription/manage': typeof AppSubscriptionManageRoute
  '/subscription/success': typeof AppSubscriptionSuccessRoute
  '/sync/$lessonId': typeof AppSyncLessonIdRoute
  '/resources/legal/privacy': typeof ResourcesLegalPrivacyRoute
  '/resources/legal/tos': typeof ResourcesLegalTosRoute
  '/resources/docs': typeof ResourcesDocsIndexRoute
  '/project/$projectId': typeof AppDesktopguardProjectProjectIdRoute
  '/subscription/comparison': typeof AppSubscriptionSubscribedguardComparisonRoute
  '/learn/$courseId/$moduleId': typeof AppHubLearnCourseIdModuleIdRoute
  '/profile/$userId/settings': typeof AppHubProfileUserIdSettingsRoute
  '/completion/$courseId/$moduleId/$lessonId': typeof AppCompletionCourseIdModuleIdLessonIdRoute
  '/profile/$userId': typeof AppHubProfileUserIdIndexRoute
  '/lesson/$courseId/$moduleId/$lessonId': typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/_app/_desktopguard': typeof AppDesktopguardRouteRouteWithChildren
  '/_app/_hub': typeof AppHubRouteRouteWithChildren
  '/_app/subscription': typeof AppSubscriptionRouteRouteWithChildren
  '/resources/legal': typeof ResourcesLegalRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/resources/landing': typeof ResourcesLandingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/subscription/_subscribedguard': typeof AppSubscriptionSubscribedguardRouteRouteWithChildren
  '/_app/_hub/courses': typeof AppHubCoursesRoute
  '/_app/_hub/leaderboard': typeof AppHubLeaderboardRoute
  '/_app/_hub/projects': typeof AppHubProjectsRoute
  '/_app/onboarding/$stage': typeof AppOnboardingStageRoute
  '/_app/subscription/already-subscribed': typeof AppSubscriptionAlreadySubscribedRoute
  '/_app/subscription/cancel': typeof AppSubscriptionCancelRoute
  '/_app/subscription/confirm': typeof AppSubscriptionConfirmRoute
  '/_app/subscription/manage': typeof AppSubscriptionManageRoute
  '/_app/subscription/success': typeof AppSubscriptionSuccessRoute
  '/_app/sync/$lessonId': typeof AppSyncLessonIdRoute
  '/resources/legal/privacy': typeof ResourcesLegalPrivacyRoute
  '/resources/legal/tos': typeof ResourcesLegalTosRoute
  '/resources/docs/': typeof ResourcesDocsIndexRoute
  '/_app/_desktopguard/project/$projectId': typeof AppDesktopguardProjectProjectIdRoute
  '/_app/_hub/profile/$userId': typeof AppHubProfileUserIdRouteWithChildren
  '/_app/subscription/_subscribedguard/comparison': typeof AppSubscriptionSubscribedguardComparisonRoute
  '/_app/lesson/$courseId/$moduleId/$lessonId': typeof AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren
  '/_app/_hub/learn/$courseId/$moduleId': typeof AppHubLearnCourseIdModuleIdRoute
  '/_app/_hub/profile/$userId/settings': typeof AppHubProfileUserIdSettingsRoute
  '/_app/completion/$courseId/$moduleId/$lessonId': typeof AppCompletionCourseIdModuleIdLessonIdRoute
  '/_app/_hub/profile/$userId/': typeof AppHubProfileUserIdIndexRoute
  '/_app/lesson/$courseId/$moduleId/$lessonId/': typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/resources'
    | '/subscription'
    | '/resources/legal'
    | '/auth/login'
    | '/auth/register'
    | '/resources/landing'
    | '/'
    | '/courses'
    | '/leaderboard'
    | '/projects'
    | '/onboarding/$stage'
    | '/subscription/already-subscribed'
    | '/subscription/cancel'
    | '/subscription/confirm'
    | '/subscription/manage'
    | '/subscription/success'
    | '/sync/$lessonId'
    | '/resources/legal/privacy'
    | '/resources/legal/tos'
    | '/resources/docs'
    | '/project/$projectId'
    | '/profile/$userId'
    | '/subscription/comparison'
    | '/lesson/$courseId/$moduleId/$lessonId'
    | '/learn/$courseId/$moduleId'
    | '/profile/$userId/settings'
    | '/completion/$courseId/$moduleId/$lessonId'
    | '/profile/$userId/'
    | '/lesson/$courseId/$moduleId/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/resources'
    | '/subscription'
    | '/resources/legal'
    | '/auth/login'
    | '/auth/register'
    | '/resources/landing'
    | '/'
    | '/courses'
    | '/leaderboard'
    | '/projects'
    | '/onboarding/$stage'
    | '/subscription/already-subscribed'
    | '/subscription/cancel'
    | '/subscription/confirm'
    | '/subscription/manage'
    | '/subscription/success'
    | '/sync/$lessonId'
    | '/resources/legal/privacy'
    | '/resources/legal/tos'
    | '/resources/docs'
    | '/project/$projectId'
    | '/subscription/comparison'
    | '/learn/$courseId/$moduleId'
    | '/profile/$userId/settings'
    | '/completion/$courseId/$moduleId/$lessonId'
    | '/profile/$userId'
    | '/lesson/$courseId/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/resources'
    | '/_app/_desktopguard'
    | '/_app/_hub'
    | '/_app/subscription'
    | '/resources/legal'
    | '/auth/login'
    | '/auth/register'
    | '/resources/landing'
    | '/_app/'
    | '/_app/subscription/_subscribedguard'
    | '/_app/_hub/courses'
    | '/_app/_hub/leaderboard'
    | '/_app/_hub/projects'
    | '/_app/onboarding/$stage'
    | '/_app/subscription/already-subscribed'
    | '/_app/subscription/cancel'
    | '/_app/subscription/confirm'
    | '/_app/subscription/manage'
    | '/_app/subscription/success'
    | '/_app/sync/$lessonId'
    | '/resources/legal/privacy'
    | '/resources/legal/tos'
    | '/resources/docs/'
    | '/_app/_desktopguard/project/$projectId'
    | '/_app/_hub/profile/$userId'
    | '/_app/subscription/_subscribedguard/comparison'
    | '/_app/lesson/$courseId/$moduleId/$lessonId'
    | '/_app/_hub/learn/$courseId/$moduleId'
    | '/_app/_hub/profile/$userId/settings'
    | '/_app/completion/$courseId/$moduleId/$lessonId'
    | '/_app/_hub/profile/$userId/'
    | '/_app/lesson/$courseId/$moduleId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ResourcesRouteRoute: typeof ResourcesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/resources/landing': {
      id: '/resources/landing'
      path: '/landing'
      fullPath: '/resources/landing'
      preLoaderRoute: typeof ResourcesLandingRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/resources/legal': {
      id: '/resources/legal'
      path: '/legal'
      fullPath: '/resources/legal'
      preLoaderRoute: typeof ResourcesLegalRouteRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub': {
      id: '/_app/_hub'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppHubRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_desktopguard': {
      id: '/_app/_desktopguard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDesktopguardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/resources/docs/': {
      id: '/resources/docs/'
      path: '/docs'
      fullPath: '/resources/docs'
      preLoaderRoute: typeof ResourcesDocsIndexRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/resources/legal/tos': {
      id: '/resources/legal/tos'
      path: '/tos'
      fullPath: '/resources/legal/tos'
      preLoaderRoute: typeof ResourcesLegalTosRouteImport
      parentRoute: typeof ResourcesLegalRouteRoute
    }
    '/resources/legal/privacy': {
      id: '/resources/legal/privacy'
      path: '/privacy'
      fullPath: '/resources/legal/privacy'
      preLoaderRoute: typeof ResourcesLegalPrivacyRouteImport
      parentRoute: typeof ResourcesLegalRouteRoute
    }
    '/_app/sync/$lessonId': {
      id: '/_app/sync/$lessonId'
      path: '/sync/$lessonId'
      fullPath: '/sync/$lessonId'
      preLoaderRoute: typeof AppSyncLessonIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/subscription/success': {
      id: '/_app/subscription/success'
      path: '/success'
      fullPath: '/subscription/success'
      preLoaderRoute: typeof AppSubscriptionSuccessRouteImport
      parentRoute: typeof AppSubscriptionRouteRoute
    }
    '/_app/subscription/manage': {
      id: '/_app/subscription/manage'
      path: '/manage'
      fullPath: '/subscription/manage'
      preLoaderRoute: typeof AppSubscriptionManageRouteImport
      parentRoute: typeof AppSubscriptionRouteRoute
    }
    '/_app/subscription/confirm': {
      id: '/_app/subscription/confirm'
      path: '/confirm'
      fullPath: '/subscription/confirm'
      preLoaderRoute: typeof AppSubscriptionConfirmRouteImport
      parentRoute: typeof AppSubscriptionRouteRoute
    }
    '/_app/subscription/cancel': {
      id: '/_app/subscription/cancel'
      path: '/cancel'
      fullPath: '/subscription/cancel'
      preLoaderRoute: typeof AppSubscriptionCancelRouteImport
      parentRoute: typeof AppSubscriptionRouteRoute
    }
    '/_app/subscription/already-subscribed': {
      id: '/_app/subscription/already-subscribed'
      path: '/already-subscribed'
      fullPath: '/subscription/already-subscribed'
      preLoaderRoute: typeof AppSubscriptionAlreadySubscribedRouteImport
      parentRoute: typeof AppSubscriptionRouteRoute
    }
    '/_app/onboarding/$stage': {
      id: '/_app/onboarding/$stage'
      path: '/onboarding/$stage'
      fullPath: '/onboarding/$stage'
      preLoaderRoute: typeof AppOnboardingStageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub/projects': {
      id: '/_app/_hub/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppHubProjectsRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_hub/leaderboard': {
      id: '/_app/_hub/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppHubLeaderboardRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_hub/courses': {
      id: '/_app/_hub/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppHubCoursesRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/subscription/_subscribedguard': {
      id: '/_app/subscription/_subscribedguard'
      path: ''
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionSubscribedguardRouteRouteImport
      parentRoute: typeof AppSubscriptionRouteRoute
    }
    '/_app/subscription/_subscribedguard/comparison': {
      id: '/_app/subscription/_subscribedguard/comparison'
      path: '/comparison'
      fullPath: '/subscription/comparison'
      preLoaderRoute: typeof AppSubscriptionSubscribedguardComparisonRouteImport
      parentRoute: typeof AppSubscriptionSubscribedguardRouteRoute
    }
    '/_app/_hub/profile/$userId': {
      id: '/_app/_hub/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppHubProfileUserIdRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_desktopguard/project/$projectId': {
      id: '/_app/_desktopguard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AppDesktopguardProjectProjectIdRouteImport
      parentRoute: typeof AppDesktopguardRouteRoute
    }
    '/_app/_hub/profile/$userId/': {
      id: '/_app/_hub/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof AppHubProfileUserIdIndexRouteImport
      parentRoute: typeof AppHubProfileUserIdRoute
    }
    '/_app/completion/$courseId/$moduleId/$lessonId': {
      id: '/_app/completion/$courseId/$moduleId/$lessonId'
      path: '/completion/$courseId/$moduleId/$lessonId'
      fullPath: '/completion/$courseId/$moduleId/$lessonId'
      preLoaderRoute: typeof AppCompletionCourseIdModuleIdLessonIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub/profile/$userId/settings': {
      id: '/_app/_hub/profile/$userId/settings'
      path: '/settings'
      fullPath: '/profile/$userId/settings'
      preLoaderRoute: typeof AppHubProfileUserIdSettingsRouteImport
      parentRoute: typeof AppHubProfileUserIdRoute
    }
    '/_app/_hub/learn/$courseId/$moduleId': {
      id: '/_app/_hub/learn/$courseId/$moduleId'
      path: '/learn/$courseId/$moduleId'
      fullPath: '/learn/$courseId/$moduleId'
      preLoaderRoute: typeof AppHubLearnCourseIdModuleIdRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/lesson/$courseId/$moduleId/$lessonId': {
      id: '/_app/lesson/$courseId/$moduleId/$lessonId'
      path: '/lesson/$courseId/$moduleId/$lessonId'
      fullPath: '/lesson/$courseId/$moduleId/$lessonId'
      preLoaderRoute: typeof AppLessonCourseIdModuleIdLessonIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lesson/$courseId/$moduleId/$lessonId/': {
      id: '/_app/lesson/$courseId/$moduleId/$lessonId/'
      path: '/'
      fullPath: '/lesson/$courseId/$moduleId/$lessonId/'
      preLoaderRoute: typeof AppLessonCourseIdModuleIdLessonIdIndexRouteImport
      parentRoute: typeof AppLessonCourseIdModuleIdLessonIdRouteRoute
    }
  }
}

interface AppDesktopguardRouteRouteChildren {
  AppDesktopguardProjectProjectIdRoute: typeof AppDesktopguardProjectProjectIdRoute
}

const AppDesktopguardRouteRouteChildren: AppDesktopguardRouteRouteChildren = {
  AppDesktopguardProjectProjectIdRoute: AppDesktopguardProjectProjectIdRoute,
}

const AppDesktopguardRouteRouteWithChildren =
  AppDesktopguardRouteRoute._addFileChildren(AppDesktopguardRouteRouteChildren)

interface AppHubProfileUserIdRouteChildren {
  AppHubProfileUserIdSettingsRoute: typeof AppHubProfileUserIdSettingsRoute
  AppHubProfileUserIdIndexRoute: typeof AppHubProfileUserIdIndexRoute
}

const AppHubProfileUserIdRouteChildren: AppHubProfileUserIdRouteChildren = {
  AppHubProfileUserIdSettingsRoute: AppHubProfileUserIdSettingsRoute,
  AppHubProfileUserIdIndexRoute: AppHubProfileUserIdIndexRoute,
}

const AppHubProfileUserIdRouteWithChildren =
  AppHubProfileUserIdRoute._addFileChildren(AppHubProfileUserIdRouteChildren)

interface AppHubRouteRouteChildren {
  AppHubCoursesRoute: typeof AppHubCoursesRoute
  AppHubLeaderboardRoute: typeof AppHubLeaderboardRoute
  AppHubProjectsRoute: typeof AppHubProjectsRoute
  AppHubProfileUserIdRoute: typeof AppHubProfileUserIdRouteWithChildren
  AppHubLearnCourseIdModuleIdRoute: typeof AppHubLearnCourseIdModuleIdRoute
}

const AppHubRouteRouteChildren: AppHubRouteRouteChildren = {
  AppHubCoursesRoute: AppHubCoursesRoute,
  AppHubLeaderboardRoute: AppHubLeaderboardRoute,
  AppHubProjectsRoute: AppHubProjectsRoute,
  AppHubProfileUserIdRoute: AppHubProfileUserIdRouteWithChildren,
  AppHubLearnCourseIdModuleIdRoute: AppHubLearnCourseIdModuleIdRoute,
}

const AppHubRouteRouteWithChildren = AppHubRouteRoute._addFileChildren(
  AppHubRouteRouteChildren,
)

interface AppSubscriptionSubscribedguardRouteRouteChildren {
  AppSubscriptionSubscribedguardComparisonRoute: typeof AppSubscriptionSubscribedguardComparisonRoute
}

const AppSubscriptionSubscribedguardRouteRouteChildren: AppSubscriptionSubscribedguardRouteRouteChildren =
  {
    AppSubscriptionSubscribedguardComparisonRoute:
      AppSubscriptionSubscribedguardComparisonRoute,
  }

const AppSubscriptionSubscribedguardRouteRouteWithChildren =
  AppSubscriptionSubscribedguardRouteRoute._addFileChildren(
    AppSubscriptionSubscribedguardRouteRouteChildren,
  )

interface AppSubscriptionRouteRouteChildren {
  AppSubscriptionSubscribedguardRouteRoute: typeof AppSubscriptionSubscribedguardRouteRouteWithChildren
  AppSubscriptionAlreadySubscribedRoute: typeof AppSubscriptionAlreadySubscribedRoute
  AppSubscriptionCancelRoute: typeof AppSubscriptionCancelRoute
  AppSubscriptionConfirmRoute: typeof AppSubscriptionConfirmRoute
  AppSubscriptionManageRoute: typeof AppSubscriptionManageRoute
  AppSubscriptionSuccessRoute: typeof AppSubscriptionSuccessRoute
}

const AppSubscriptionRouteRouteChildren: AppSubscriptionRouteRouteChildren = {
  AppSubscriptionSubscribedguardRouteRoute:
    AppSubscriptionSubscribedguardRouteRouteWithChildren,
  AppSubscriptionAlreadySubscribedRoute: AppSubscriptionAlreadySubscribedRoute,
  AppSubscriptionCancelRoute: AppSubscriptionCancelRoute,
  AppSubscriptionConfirmRoute: AppSubscriptionConfirmRoute,
  AppSubscriptionManageRoute: AppSubscriptionManageRoute,
  AppSubscriptionSuccessRoute: AppSubscriptionSuccessRoute,
}

const AppSubscriptionRouteRouteWithChildren =
  AppSubscriptionRouteRoute._addFileChildren(AppSubscriptionRouteRouteChildren)

interface AppLessonCourseIdModuleIdLessonIdRouteRouteChildren {
  AppLessonCourseIdModuleIdLessonIdIndexRoute: typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}

const AppLessonCourseIdModuleIdLessonIdRouteRouteChildren: AppLessonCourseIdModuleIdLessonIdRouteRouteChildren =
  {
    AppLessonCourseIdModuleIdLessonIdIndexRoute:
      AppLessonCourseIdModuleIdLessonIdIndexRoute,
  }

const AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren =
  AppLessonCourseIdModuleIdLessonIdRouteRoute._addFileChildren(
    AppLessonCourseIdModuleIdLessonIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppDesktopguardRouteRoute: typeof AppDesktopguardRouteRouteWithChildren
  AppHubRouteRoute: typeof AppHubRouteRouteWithChildren
  AppSubscriptionRouteRoute: typeof AppSubscriptionRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOnboardingStageRoute: typeof AppOnboardingStageRoute
  AppSyncLessonIdRoute: typeof AppSyncLessonIdRoute
  AppLessonCourseIdModuleIdLessonIdRouteRoute: typeof AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren
  AppCompletionCourseIdModuleIdLessonIdRoute: typeof AppCompletionCourseIdModuleIdLessonIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDesktopguardRouteRoute: AppDesktopguardRouteRouteWithChildren,
  AppHubRouteRoute: AppHubRouteRouteWithChildren,
  AppSubscriptionRouteRoute: AppSubscriptionRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOnboardingStageRoute: AppOnboardingStageRoute,
  AppSyncLessonIdRoute: AppSyncLessonIdRoute,
  AppLessonCourseIdModuleIdLessonIdRouteRoute:
    AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren,
  AppCompletionCourseIdModuleIdLessonIdRoute:
    AppCompletionCourseIdModuleIdLessonIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ResourcesLegalRouteRouteChildren {
  ResourcesLegalPrivacyRoute: typeof ResourcesLegalPrivacyRoute
  ResourcesLegalTosRoute: typeof ResourcesLegalTosRoute
}

const ResourcesLegalRouteRouteChildren: ResourcesLegalRouteRouteChildren = {
  ResourcesLegalPrivacyRoute: ResourcesLegalPrivacyRoute,
  ResourcesLegalTosRoute: ResourcesLegalTosRoute,
}

const ResourcesLegalRouteRouteWithChildren =
  ResourcesLegalRouteRoute._addFileChildren(ResourcesLegalRouteRouteChildren)

interface ResourcesRouteRouteChildren {
  ResourcesLegalRouteRoute: typeof ResourcesLegalRouteRouteWithChildren
  ResourcesLandingRoute: typeof ResourcesLandingRoute
  ResourcesDocsIndexRoute: typeof ResourcesDocsIndexRoute
}

const ResourcesRouteRouteChildren: ResourcesRouteRouteChildren = {
  ResourcesLegalRouteRoute: ResourcesLegalRouteRouteWithChildren,
  ResourcesLandingRoute: ResourcesLandingRoute,
  ResourcesDocsIndexRoute: ResourcesDocsIndexRoute,
}

const ResourcesRouteRouteWithChildren = ResourcesRouteRoute._addFileChildren(
  ResourcesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ResourcesRouteRoute: ResourcesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
