/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHubRouteRouteImport } from './routes/_app/_hub/route'
import { Route as AppDesktopguardRouteRouteImport } from './routes/_app/_desktopguard/route'
import { Route as AppSyncLessonIdRouteImport } from './routes/_app/sync/$lessonId'
import { Route as AppOnboardingStageRouteImport } from './routes/_app/onboarding.$stage'
import { Route as AppHubProjectsRouteImport } from './routes/_app/_hub/projects'
import { Route as AppHubCoursesRouteImport } from './routes/_app/_hub/courses'
import { Route as AppHubBuilderRouteImport } from './routes/_app/_hub/builder'
import { Route as AppHubProfileUserIdRouteImport } from './routes/_app/_hub/profile/$userId'
import { Route as AppDesktopguardProjectProjectIdRouteImport } from './routes/_app/_desktopguard/project/$projectId'
import { Route as AppDesktopguardBuildCourseIdRouteImport } from './routes/_app/_desktopguard/build/$courseId'
import { Route as AppCompletionCourseIdModuleIdLessonIdRouteImport } from './routes/_app/completion/$courseId/$moduleId/$lessonId'
import { Route as AppHubLearnCourseIdModuleIdRouteImport } from './routes/_app/_hub/learn/$courseId/$moduleId'
import { Route as AppLessonCourseIdModuleIdLessonIdRouteRouteImport } from './routes/_app/lesson/$courseId/$moduleId/$lessonId/route'
import { Route as AppLessonCourseIdModuleIdLessonIdIndexRouteImport } from './routes/_app/lesson/$courseId/$moduleId/$lessonId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubRouteRoute = AppHubRouteRouteImport.update({
  id: '/_hub',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDesktopguardRouteRoute = AppDesktopguardRouteRouteImport.update({
  id: '/_desktopguard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSyncLessonIdRoute = AppSyncLessonIdRouteImport.update({
  id: '/sync/$lessonId',
  path: '/sync/$lessonId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingStageRoute = AppOnboardingStageRouteImport.update({
  id: '/onboarding/$stage',
  path: '/onboarding/$stage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHubProjectsRoute = AppHubProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubCoursesRoute = AppHubCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubBuilderRoute = AppHubBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppHubProfileUserIdRoute = AppHubProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppHubRouteRoute,
} as any)
const AppDesktopguardProjectProjectIdRoute =
  AppDesktopguardProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AppDesktopguardRouteRoute,
  } as any)
const AppDesktopguardBuildCourseIdRoute =
  AppDesktopguardBuildCourseIdRouteImport.update({
    id: '/build/$courseId',
    path: '/build/$courseId',
    getParentRoute: () => AppDesktopguardRouteRoute,
  } as any)
const AppCompletionCourseIdModuleIdLessonIdRoute =
  AppCompletionCourseIdModuleIdLessonIdRouteImport.update({
    id: '/completion/$courseId/$moduleId/$lessonId',
    path: '/completion/$courseId/$moduleId/$lessonId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppHubLearnCourseIdModuleIdRoute =
  AppHubLearnCourseIdModuleIdRouteImport.update({
    id: '/learn/$courseId/$moduleId',
    path: '/learn/$courseId/$moduleId',
    getParentRoute: () => AppHubRouteRoute,
  } as any)
const AppLessonCourseIdModuleIdLessonIdRouteRoute =
  AppLessonCourseIdModuleIdLessonIdRouteRouteImport.update({
    id: '/lesson/$courseId/$moduleId/$lessonId',
    path: '/lesson/$courseId/$moduleId/$lessonId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLessonCourseIdModuleIdLessonIdIndexRoute =
  AppLessonCourseIdModuleIdLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLessonCourseIdModuleIdLessonIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/demo': typeof DemoIndexRoute
  '/builder': typeof AppHubBuilderRoute
  '/courses': typeof AppHubCoursesRoute
  '/projects': typeof AppHubProjectsRoute
  '/onboarding/$stage': typeof AppOnboardingStageRoute
  '/sync/$lessonId': typeof AppSyncLessonIdRoute
  '/build/$courseId': typeof AppDesktopguardBuildCourseIdRoute
  '/project/$projectId': typeof AppDesktopguardProjectProjectIdRoute
  '/profile/$userId': typeof AppHubProfileUserIdRoute
  '/lesson/$courseId/$moduleId/$lessonId': typeof AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren
  '/learn/$courseId/$moduleId': typeof AppHubLearnCourseIdModuleIdRoute
  '/completion/$courseId/$moduleId/$lessonId': typeof AppCompletionCourseIdModuleIdLessonIdRoute
  '/lesson/$courseId/$moduleId/$lessonId/': typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/demo': typeof DemoIndexRoute
  '/builder': typeof AppHubBuilderRoute
  '/courses': typeof AppHubCoursesRoute
  '/projects': typeof AppHubProjectsRoute
  '/onboarding/$stage': typeof AppOnboardingStageRoute
  '/sync/$lessonId': typeof AppSyncLessonIdRoute
  '/build/$courseId': typeof AppDesktopguardBuildCourseIdRoute
  '/project/$projectId': typeof AppDesktopguardProjectProjectIdRoute
  '/profile/$userId': typeof AppHubProfileUserIdRoute
  '/learn/$courseId/$moduleId': typeof AppHubLearnCourseIdModuleIdRoute
  '/completion/$courseId/$moduleId/$lessonId': typeof AppCompletionCourseIdModuleIdLessonIdRoute
  '/lesson/$courseId/$moduleId/$lessonId': typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_desktopguard': typeof AppDesktopguardRouteRouteWithChildren
  '/_app/_hub': typeof AppHubRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/_app/_hub/builder': typeof AppHubBuilderRoute
  '/_app/_hub/courses': typeof AppHubCoursesRoute
  '/_app/_hub/projects': typeof AppHubProjectsRoute
  '/_app/onboarding/$stage': typeof AppOnboardingStageRoute
  '/_app/sync/$lessonId': typeof AppSyncLessonIdRoute
  '/_app/_desktopguard/build/$courseId': typeof AppDesktopguardBuildCourseIdRoute
  '/_app/_desktopguard/project/$projectId': typeof AppDesktopguardProjectProjectIdRoute
  '/_app/_hub/profile/$userId': typeof AppHubProfileUserIdRoute
  '/_app/lesson/$courseId/$moduleId/$lessonId': typeof AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren
  '/_app/_hub/learn/$courseId/$moduleId': typeof AppHubLearnCourseIdModuleIdRoute
  '/_app/completion/$courseId/$moduleId/$lessonId': typeof AppCompletionCourseIdModuleIdLessonIdRoute
  '/_app/lesson/$courseId/$moduleId/$lessonId/': typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/builder'
    | '/courses'
    | '/projects'
    | '/onboarding/$stage'
    | '/sync/$lessonId'
    | '/build/$courseId'
    | '/project/$projectId'
    | '/profile/$userId'
    | '/lesson/$courseId/$moduleId/$lessonId'
    | '/learn/$courseId/$moduleId'
    | '/completion/$courseId/$moduleId/$lessonId'
    | '/lesson/$courseId/$moduleId/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/builder'
    | '/courses'
    | '/projects'
    | '/onboarding/$stage'
    | '/sync/$lessonId'
    | '/build/$courseId'
    | '/project/$projectId'
    | '/profile/$userId'
    | '/learn/$courseId/$moduleId'
    | '/completion/$courseId/$moduleId/$lessonId'
    | '/lesson/$courseId/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_desktopguard'
    | '/_app/_hub'
    | '/_app/'
    | '/auth/'
    | '/demo/'
    | '/_app/_hub/builder'
    | '/_app/_hub/courses'
    | '/_app/_hub/projects'
    | '/_app/onboarding/$stage'
    | '/_app/sync/$lessonId'
    | '/_app/_desktopguard/build/$courseId'
    | '/_app/_desktopguard/project/$projectId'
    | '/_app/_hub/profile/$userId'
    | '/_app/lesson/$courseId/$moduleId/$lessonId'
    | '/_app/_hub/learn/$courseId/$moduleId'
    | '/_app/completion/$courseId/$moduleId/$lessonId'
    | '/_app/lesson/$courseId/$moduleId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub': {
      id: '/_app/_hub'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppHubRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_desktopguard': {
      id: '/_app/_desktopguard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDesktopguardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sync/$lessonId': {
      id: '/_app/sync/$lessonId'
      path: '/sync/$lessonId'
      fullPath: '/sync/$lessonId'
      preLoaderRoute: typeof AppSyncLessonIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding/$stage': {
      id: '/_app/onboarding/$stage'
      path: '/onboarding/$stage'
      fullPath: '/onboarding/$stage'
      preLoaderRoute: typeof AppOnboardingStageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub/projects': {
      id: '/_app/_hub/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppHubProjectsRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_hub/courses': {
      id: '/_app/_hub/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppHubCoursesRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_hub/builder': {
      id: '/_app/_hub/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppHubBuilderRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_hub/profile/$userId': {
      id: '/_app/_hub/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppHubProfileUserIdRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/_desktopguard/project/$projectId': {
      id: '/_app/_desktopguard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AppDesktopguardProjectProjectIdRouteImport
      parentRoute: typeof AppDesktopguardRouteRoute
    }
    '/_app/_desktopguard/build/$courseId': {
      id: '/_app/_desktopguard/build/$courseId'
      path: '/build/$courseId'
      fullPath: '/build/$courseId'
      preLoaderRoute: typeof AppDesktopguardBuildCourseIdRouteImport
      parentRoute: typeof AppDesktopguardRouteRoute
    }
    '/_app/completion/$courseId/$moduleId/$lessonId': {
      id: '/_app/completion/$courseId/$moduleId/$lessonId'
      path: '/completion/$courseId/$moduleId/$lessonId'
      fullPath: '/completion/$courseId/$moduleId/$lessonId'
      preLoaderRoute: typeof AppCompletionCourseIdModuleIdLessonIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_hub/learn/$courseId/$moduleId': {
      id: '/_app/_hub/learn/$courseId/$moduleId'
      path: '/learn/$courseId/$moduleId'
      fullPath: '/learn/$courseId/$moduleId'
      preLoaderRoute: typeof AppHubLearnCourseIdModuleIdRouteImport
      parentRoute: typeof AppHubRouteRoute
    }
    '/_app/lesson/$courseId/$moduleId/$lessonId': {
      id: '/_app/lesson/$courseId/$moduleId/$lessonId'
      path: '/lesson/$courseId/$moduleId/$lessonId'
      fullPath: '/lesson/$courseId/$moduleId/$lessonId'
      preLoaderRoute: typeof AppLessonCourseIdModuleIdLessonIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lesson/$courseId/$moduleId/$lessonId/': {
      id: '/_app/lesson/$courseId/$moduleId/$lessonId/'
      path: '/'
      fullPath: '/lesson/$courseId/$moduleId/$lessonId/'
      preLoaderRoute: typeof AppLessonCourseIdModuleIdLessonIdIndexRouteImport
      parentRoute: typeof AppLessonCourseIdModuleIdLessonIdRouteRoute
    }
  }
}

interface AppDesktopguardRouteRouteChildren {
  AppDesktopguardBuildCourseIdRoute: typeof AppDesktopguardBuildCourseIdRoute
  AppDesktopguardProjectProjectIdRoute: typeof AppDesktopguardProjectProjectIdRoute
}

const AppDesktopguardRouteRouteChildren: AppDesktopguardRouteRouteChildren = {
  AppDesktopguardBuildCourseIdRoute: AppDesktopguardBuildCourseIdRoute,
  AppDesktopguardProjectProjectIdRoute: AppDesktopguardProjectProjectIdRoute,
}

const AppDesktopguardRouteRouteWithChildren =
  AppDesktopguardRouteRoute._addFileChildren(AppDesktopguardRouteRouteChildren)

interface AppHubRouteRouteChildren {
  AppHubBuilderRoute: typeof AppHubBuilderRoute
  AppHubCoursesRoute: typeof AppHubCoursesRoute
  AppHubProjectsRoute: typeof AppHubProjectsRoute
  AppHubProfileUserIdRoute: typeof AppHubProfileUserIdRoute
  AppHubLearnCourseIdModuleIdRoute: typeof AppHubLearnCourseIdModuleIdRoute
}

const AppHubRouteRouteChildren: AppHubRouteRouteChildren = {
  AppHubBuilderRoute: AppHubBuilderRoute,
  AppHubCoursesRoute: AppHubCoursesRoute,
  AppHubProjectsRoute: AppHubProjectsRoute,
  AppHubProfileUserIdRoute: AppHubProfileUserIdRoute,
  AppHubLearnCourseIdModuleIdRoute: AppHubLearnCourseIdModuleIdRoute,
}

const AppHubRouteRouteWithChildren = AppHubRouteRoute._addFileChildren(
  AppHubRouteRouteChildren,
)

interface AppLessonCourseIdModuleIdLessonIdRouteRouteChildren {
  AppLessonCourseIdModuleIdLessonIdIndexRoute: typeof AppLessonCourseIdModuleIdLessonIdIndexRoute
}

const AppLessonCourseIdModuleIdLessonIdRouteRouteChildren: AppLessonCourseIdModuleIdLessonIdRouteRouteChildren =
  {
    AppLessonCourseIdModuleIdLessonIdIndexRoute:
      AppLessonCourseIdModuleIdLessonIdIndexRoute,
  }

const AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren =
  AppLessonCourseIdModuleIdLessonIdRouteRoute._addFileChildren(
    AppLessonCourseIdModuleIdLessonIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppDesktopguardRouteRoute: typeof AppDesktopguardRouteRouteWithChildren
  AppHubRouteRoute: typeof AppHubRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOnboardingStageRoute: typeof AppOnboardingStageRoute
  AppSyncLessonIdRoute: typeof AppSyncLessonIdRoute
  AppLessonCourseIdModuleIdLessonIdRouteRoute: typeof AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren
  AppCompletionCourseIdModuleIdLessonIdRoute: typeof AppCompletionCourseIdModuleIdLessonIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDesktopguardRouteRoute: AppDesktopguardRouteRouteWithChildren,
  AppHubRouteRoute: AppHubRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOnboardingStageRoute: AppOnboardingStageRoute,
  AppSyncLessonIdRoute: AppSyncLessonIdRoute,
  AppLessonCourseIdModuleIdLessonIdRouteRoute:
    AppLessonCourseIdModuleIdLessonIdRouteRouteWithChildren,
  AppCompletionCourseIdModuleIdLessonIdRoute:
    AppCompletionCourseIdModuleIdLessonIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
